# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ff611a9fca971d5d85f676e3bbf4625ef74d1ec5ffd725ba75bfcd60a91633f9f458e4edc9067b44ef2f992784a59767052c7275934bdb3627205ade85f0510b

test:
  secret_key_base: 975eec9f9e5fa36f3aef9824648f0a1391e564dee037c6bb3274cf0c933005a037bc855a2de804d5bb1c6b1515884c3802359f0d616dd45b354ecbd62bb1cdad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
